name: blog_app_bloc
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flutter_bloc: ^5.0.1
  cloud_firestore: ^0.13.7
  firebase_storage: ^3.1.6
  equatable: ^1.2.0
  intl: ^0.16.1
  image_picker: ^0.6.7+4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true